title:              Clean Blog
email:              b419006@iiit-bh.ac.in
description:        A Blog Theme by Start Bootstrap
author:             Start Bootstrap
baseurl:            "/A"
url:                "https://Abhineel-Nandi.github.io/A"

# Social Profiles
twitter_username:   
github_username:    Abhineel-Nandi
facebook_username:  abhineel.nandi.3
linkedin_username:  abhineel-nandi-0004

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-167948900-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap 
